#!/usr/bin/env python3
"""One-time bootstrap of the local GitLab: users, tokens, group, project, glab auth.

Idempotent and state-deriving — safe to run repeatedly. Verified against GitLab 19.2.1.

Two deliberate design choices, both learned the hard way:

* **Only the root token is minted via `gitlab-rails`.** A rails runner boots a second
  full Rails app (~1.5 GB); in a 6 GB VM that OOM-kills the whole VM (taking the docker
  daemon with it), so puma+sidekiq are stopped for the duration. Everything else goes
  through the REST API.
* **Users are created via the API, never via `User.new(...).save!` in rails** — that
  bypasses personal-namespace creation and fails with "Namespace can't be blank".
  The API uses GitLab's own service and gets it right.

Run `docker compose up -d` first, then:  python3 bootstrap.py

Fixture data (branches, MRs, threads) is NOT created here — that is fixture.py.
"""
import datetime
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request

# Repo root, 2 levels up from e2e/bootstrap.py — needed so `lib/` is importable.
_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from lib.cli import die  # noqa: E402

HOST = "gitlab.test"
URL = f"http://{HOST}"
API = f"{URL}/api/v4"
CONTAINER = "e2e-gitlab"

GROUP = "demo"
PROJECT = "bulletproof-react"
PASSWORD = "Ud5jH3-wN7cY2-qF4tM8"
ROOT_PASSWORD = "Rk8xQ2-mT9zV4-pB6nL1"
PAT_NAME = "e2e-fixture"

# username -> (display name, project access level). Display names use the enterprise
# "Last, First - ID" shape on purpose: lib/mr_common.py's first_name() has a parser for
# exactly that, so the fixture exercises the real code path instead of a happy-path name.
# frank needs Maintainer (40) to force-push MR !3's branch, which /rework-mr does on
# every fixup; the bots only need Developer (30).
USERS = {
    "frank": ("Blendinger, Frank - AB12345", 40),        # the live identity — you
    "author-bot": ("Novak, Alex - CD67890", 30),          # authors MR !1 and !2
    "reviewer-bot": ("Haas, Miriam - EF13579", 30),       # reviews MR !3
    "peer-bot": ("Okonkwo, Chidi - GH24680", 30),         # one extra thread on MR !2
}

HERE = os.path.dirname(os.path.abspath(__file__))
ENV_FILE = os.path.join(HERE, ".env.local")


def root_token():
    """Deterministic so a re-run never strands it: 'glpat-' + exactly 20 chars."""
    return "glpat-" + "e2erootfixture0000000"[:20]


def expires_at():
    """GitLab caps PAT lifetime at 365 days; stay just inside."""
    return (datetime.date.today() + datetime.timedelta(days=360)).isoformat()


def step(msg):
    print(f"==> {msg}", flush=True)


def sh(cmd, **kw):
    return subprocess.run(cmd, capture_output=True, text=True, **kw)


# ---------------------------------------------------------------- env file


def read_env():
    if not os.path.exists(ENV_FILE):
        return {}
    out = {}
    with open(ENV_FILE) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                out[k] = v
    return out


def env_key(username):
    return f"E2E_TOKEN_{username.replace('-', '_').upper()}"


def write_env(tokens):
    lines = ["# generated by bootstrap.py — gitignored, local only",
             f"E2E_GITLAB_HOST={HOST}", f"E2E_GITLAB_URL={URL}",
             f"E2E_PROJECT={GROUP}/{PROJECT}",
             f"E2E_PASSWORD={PASSWORD}"]
    lines += [f"{env_key(u)}={t}" for u, t in tokens.items()]
    with open(ENV_FILE, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(ENV_FILE, 0o600)
    print(f"    wrote {ENV_FILE}")


# ---------------------------------------------------------------- preflight


def check_hosts():
    try:
        with open("/etc/hosts") as f:
            hosts = f.read()
    except OSError as e:
        die(f"cannot read /etc/hosts: {e}")
    for line in hosts.splitlines():
        line = line.split("#", 1)[0]
        if HOST in line.split() and line.strip().startswith("127."):
            return
    die(f"/etc/hosts has no entry for {HOST}. Needs sudo, so run it yourself:\n"
        f'    sudo sh -c \'echo "127.0.0.1 {HOST}" >> /etc/hosts\'')


def check_container():
    r = sh(["docker", "inspect", "-f", "{{.State.Running}}", CONTAINER])
    if r.returncode != 0 or r.stdout.strip() != "true":
        die(f"container {CONTAINER} is not running — `docker compose up -d` first")


def wait_ready(timeout=900, quiet=False):
    """Probes /users/sign_in, NOT /-/readiness: the readiness endpoint is IP-allowlisted
    to 127.0.0.1, so a request from the host always gets a 404 and never looks ready."""
    if not quiet:
        step("waiting for GitLab (first boot takes 3-5 min)")
    deadline = time.time() + timeout
    last = ""
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(f"{URL}/users/sign_in", timeout=10) as r:
                if r.status == 200:
                    if not quiet:
                        print("    ready")
                    return
        except Exception as e:                    # noqa: BLE001 — any failure = not up
            msg = type(e).__name__
            if msg != last and not quiet:
                print(f"    …{msg}", flush=True)
                last = msg
        time.sleep(10)
    die("GitLab did not become ready in time — check `docker compose logs -f gitlab`")


# ---------------------------------------------------------------- api


def api(path, method="GET", body=None, token=None):
    req = urllib.request.Request(
        f"{API}/{path.lstrip('/')}", method=method,
        data=json.dumps(body).encode() if body is not None else None,
        headers={"PRIVATE-TOKEN": token or root_token(),
                 "Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=60) as r:
            raw = r.read().decode()
            return json.loads(raw) if raw else None
    except urllib.error.HTTPError as e:
        detail = e.read().decode()[:400]
        raise RuntimeError(f"{method} {path} -> {e.code}: {detail}") from None


# ---------------------------------------------------------------- root token


RAILS_ROOT_TOKEN = """
u = User.find_by_username('root')
raise 'no root user' unless u
t = u.personal_access_tokens.find_by(name: %(name)r)
t ||= u.personal_access_tokens.new(name: %(name)r,
                                   scopes: ['api', 'write_repository'],
                                   expires_at: %(exp)r)
t.set_token(%(raw)r)
t.save!
puts 'root token ok'
"""


def have_root_token():
    try:
        return api("user").get("username") == "root"
    except RuntimeError:
        return False


def mint_root_token():
    if have_root_token():
        print("    root token already valid — skipping rails")
        return
    step("minting root token via rails (~60 s, puma paused to free memory)")
    script = RAILS_ROOT_TOKEN % {"name": PAT_NAME, "exp": expires_at(),
                                 "raw": root_token()}
    sh(["docker", "exec", CONTAINER, "gitlab-ctl", "stop", "puma"])
    sh(["docker", "exec", CONTAINER, "gitlab-ctl", "stop", "sidekiq"])
    try:
        r = sh(["docker", "exec", "-i", CONTAINER, "gitlab-rails", "runner", "-"],
               input=script)
    finally:
        # Load-bearing: leaving puma stopped would look like a dead GitLab.
        sh(["docker", "exec", CONTAINER, "gitlab-ctl", "start", "puma"])
        sh(["docker", "exec", CONTAINER, "gitlab-ctl", "start", "sidekiq"])
    if r.returncode != 0 or "root token ok" not in r.stdout:
        die("minting the root token failed:\n"
            + (r.stderr.strip() or r.stdout.strip())[:1500])
    print("    root token minted")
    wait_ready(timeout=300, quiet=True)
    if not have_root_token():
        die("root token minted but the API rejects it")


# ---------------------------------------------------------------- users


def find_user(username):
    hits = api(f"users?username={username}") or []
    return hits[0] if hits else None


def ensure_users():
    step("ensuring users")
    ids = {}
    for uname, (dname, _lvl) in USERS.items():
        u = find_user(uname)
        if not u:
            u = api("users", "POST", {
                "username": uname, "name": dname, "email": f"{uname}@e2e.test",
                "password": PASSWORD, "skip_confirmation": True,
                "can_create_group": False,
            })
            print(f"    created {uname}")
        ids[uname] = u["id"]
    return ids


def token_valid(username, token):
    if not token:
        return False
    try:
        return api("user", token=token).get("username") == username
    except RuntimeError:
        return False


def ensure_tokens(ids):
    """Reuse a stored token when it still authenticates; otherwise mint a new one via
    the admin endpoint. The value is only ever returned at creation time, which is why
    it has to be persisted to .env.local rather than re-derived."""
    step("ensuring personal access tokens")
    env = read_env()
    tokens = {"root": root_token()}
    for uname in USERS:
        stored = env.get(env_key(uname))
        if token_valid(uname, stored):
            tokens[uname] = stored
            continue
        t = api(f"users/{ids[uname]}/personal_access_tokens", "POST", {
            "name": PAT_NAME, "scopes": ["api", "write_repository"],
            "expires_at": expires_at()})
        tokens[uname] = t["token"]
        print(f"    minted token for {uname}")
    return tokens


# ---------------------------------------------------------------- project


def ensure_group():
    for g in api(f"groups?search={GROUP}") or []:
        if g["path"] == GROUP:
            return g["id"]
    step(f"creating group {GROUP}")
    return api("groups", "POST", {"name": GROUP, "path": GROUP,
                                  "visibility": "internal"})["id"]


def ensure_project(group_id):
    """fixture.py deletes and recreates the project on every reset (that is what
    restarts MR IIDs at 1); here we only guarantee it exists at all."""
    try:
        return api(f"projects/{GROUP}%2F{PROJECT}")["id"]
    except RuntimeError:
        pass
    step(f"creating project {GROUP}/{PROJECT}")
    return api("projects", "POST", {
        "name": PROJECT, "path": PROJECT, "namespace_id": group_id,
        "default_branch": "main", "visibility": "internal",
        "initialize_with_readme": False,
        "merge_requests_enabled": True, "issues_enabled": False,
        "wiki_enabled": False, "snippets_enabled": False,
        "container_registry_enabled": False, "packages_enabled": False,
        "builds_access_level": "disabled",          # no CI by design
        "only_allow_merge_if_all_discussions_are_resolved": False,
        "remove_source_branch_after_merge": True,
    })["id"]


def ensure_members(project_id, ids):
    have = {m["username"]: m for m in api(f"projects/{project_id}/members") or []}
    for uname, (_dname, level) in USERS.items():
        if uname in have and have[uname]["access_level"] >= level:
            continue
        if uname in have:
            api(f"projects/{project_id}/members/{ids[uname]}", "PUT",
                {"access_level": level})
        else:
            api(f"projects/{project_id}/members", "POST",
                {"user_id": ids[uname], "access_level": level})
        print(f"    member {uname} -> {level}")


# ---------------------------------------------------------------- glab


def configure_glab(tokens):
    """--insecure-storage on purpose: the macOS keyring prompts interactively, which
    would hang an unattended reset."""
    step(f"configuring glab for {HOST} (http)")
    r = sh(["glab", "auth", "login", "--hostname", HOST,
            "--api-protocol", "http", "--git-protocol", "http",
            "--insecure-storage", "--stdin"], input=tokens["frank"])
    if r.returncode != 0:
        die(f"glab auth login failed: {r.stderr.strip()}")
    r = sh(["glab", "api", "user"], env={**os.environ, "GITLAB_HOST": HOST})
    if r.returncode != 0:
        die(f"glab cannot reach {HOST}: {r.stderr.strip()}")
    who = json.loads(r.stdout)
    print(f"    glab authenticated as {who['username']} ({who['name']})")


def main():
    check_hosts()
    check_container()
    wait_ready()
    mint_root_token()
    ids = ensure_users()
    tokens = ensure_tokens(ids)
    gid = ensure_group()
    pid = ensure_project(gid)
    ensure_members(pid, ids)
    configure_glab(tokens)
    write_env(tokens)
    step("bootstrap complete")
    print(f"    {URL}/{GROUP}/{PROJECT}")
    print(f"    root login:    root / {ROOT_PASSWORD}")
    print(f"    browser login: frank / {PASSWORD}")
    print("    next: python3 fixture.py")


if __name__ == "__main__":
    main()
